version: '3.9'

services:
  test:
    image: dockercli
    network_mode: host
    volumes:
      # Mount the docker socket to allow docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["sh test.sh"]
